### ISSUE TITLE
Can't update api 

### ISSUE THREAD

**Issue by lenguyenthimy-agilityio** [drf-tools/drf-app-generators#1]
When run `app_update` command, can't update apis, only update database

**Comment by huytr4n** [comment]
@lenguyen-agilityio This is fixed on the version 0.0.5. Please check out the README again. I also added option to update serializers and unit test.
https://pypi.org/project/drf-app-generators/

**Comment by lenguyenthimy-agilityio** [comment]
@tranquochuy It's work
