### ISSUE TITLE
Can't generator class  camel case format

### ISSUE THREAD

**Issue by lenguyenthimy-agilityio** [drf-tools/drf-app-generators#2]
Can't generator class  camel case format. Example: Class name expected SubCategory, but result is Subcategory

**Comment by huytr4n** [comment]
@lenguyen-agilityio This is fixed on version 0.0.4. Please install it with the following comment.
```
pip install drf-app-generators==0.0.4
```

**Comment by lenguyenthimy-agilityio** [comment]
@tranquochuy It's work
