### ISSUE TITLE
Can't update admin

### ISSUE THREAD

**Issue by lenguyenthimy-agilityio** [drf-tools/drf-app-generators#5]
Can't update admin when rename field model. 
Ex: I generator app `rewards` and `Reward` model has field with name is `name`, after update `rewards` app, I change `name` to `name_reward` and  update app again `bin/dj.sh app_update rewards --admin` got error `<class 'rewards.admin.RewardAdmin'>: (admin.E108) The value of 'list_display[0]' refers to 'name', which is not a callable, an attribute of 'RewardAdmin', or an attribute or method on 'rewards.Reward'.`

**Comment by huytr4n** [comment]
@lenguyen-agilityio This should be fixed on the latest version.
